# Base image
FROM mongo:latest

# Set the working directory
WORKDIR /data

# Copy the MongoDB configuration file to the container
COPY mongod.conf /etc/mongod.conf

# Expose the MongoDB port
EXPOSE 27017

# Start the MongoDB server when the container starts
CMD ["mongod", "--config", "/etc/mongod.conf"]
