networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.0.86/24
      driver: default
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    depends_on:
    - db
    networks:
    - mynetwork
  db:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    ports:
    - 27017:27017
version: '3.9'
