version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    ports:
      - "27017:27017"

  app:
    build:
      context: .
      dockerfile: Dockerfile-python
    depends_on:
      - db
