# Base image
FROM python:alpine

# Install python/pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt requirements.txt
RUN apk add build-base linux-headers
RUN apk add nmap
RUN pip install -r requirements.txt


# Copy the python script to the working directory
COPY core core
COPY scans scans
COPY main.py main.py
COPY config.ini config.ini

# Run the python script when the container starts
CMD ["python", "main.py"]